# This section controls CHANGELOG.md appearance
[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
body = """
{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}](https://github.com/vofronte/vue-glimpse/compare/{{ previous.version }}...{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}\
    ### {{ group | striptags | trim }}
    {% for commit in commits %}\
        - {% if commit.scope %}\
            **{{ commit.scope }}:** \
          {% endif %}\
          {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/vofronte/vue-glimpse/commit/{{ commit.id }}))\
    {% endfor %}\
{% endfor %}\n
"""
trim = true
footer = "<!-- generated by git-cliff -->"

[bump]
initial_tag = "v0.1.0"

# This section controls commit parsing
[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
# Organized and clean commit groups
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->âœ¨ Features" },
  { message = "^fix", group = "<!-- 1 -->ğŸ› Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->âš¡ Performance" },
  { message = "^refactor", group = "<!-- 3 -->â™»ï¸ Refactor" },
  { message = "^docs", group = "<!-- 4 -->ğŸ“ Documentation" },
  { message = "^style", group = "<!-- 5 -->ğŸ’„ Styling" },
  { message = "^test", group = "<!-- 6 -->âœ… Testing" },
  { message = "^chore\\(release\\):", skip = true },
  { message = "^chore\\(deps", skip = true },
  { message = "^chore", group = "<!-- 7 -->ğŸ§¹ Miscellaneous Chores" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "newest"
